{% set version = "1.1-11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mixsmsn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mixsmsn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mixsmsn/mixsmsn_{{ version }}.tar.gz
  sha256: f37864c0ef2b4c409ef26051f0196af84d95936a64935cc8054c917d8f5423c4

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mvtnorm >=0.9_9
  run:
    - r-base
    - r-mvtnorm >=0.9_9

test:
  commands:
    - $R -e "library('mixsmsn')"           # [not win]
    - "\"%R%\" -e \"library('mixsmsn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mixsmsn
  license: GPL-2.0-or-later
  summary: 'Functions to fit finite mixture of scale mixture of skew-normal (FM-SMSN) distributions, details in Prates, Lachos and Cabral (2013) <doi: 10.18637/jss.v054.i12>, Cabral, Lachos and Prates (2012) <doi:10.1016/j.csda.2011.06.026> and Basso, Lachos, Cabral and Ghosh (2010) <doi:10.1016/j.csda.2009.09.031>.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mixsmsn
# Title: Fitting Finite Mixture of Scale Mixture of Skew-Normal Distributions
# Date: 2019-10-21
# Version: 1.1-6
# Authors@R: c(person("Marcos", "Prates", role=c("aut","cre","trl"), email="marcosop@est.ufmg.br"), person("Victor", "Lachos", role="aut"), person("Celso", "Cabral", role="aut"))
# Description: Functions to fit finite mixture of scale mixture of skew-normal (FM-SMSN) distributions, details in Prates, Lachos and Cabral (2013) <doi: 10.18637/jss.v054.i12>, Cabral, Lachos and Prates (2012) <doi:10.1016/j.csda.2011.06.026> and Basso, Lachos, Cabral and Ghosh (2010) <doi:10.1016/j.csda.2009.09.031>.
# Depends: R (>= 1.9.0), mvtnorm (>= 0.9-9)
# Author: Marcos Prates [aut, cre, trl], Victor Lachos [aut], Celso Cabral [aut]
# Maintainer: Marcos Prates <marcosop@est.ufmg.br>
# License: GPL (>= 2.0)
# Packaged: 2019-10-22 01:18:41 UTC; marcos
# Repository: CRAN
# NeedsCompilation: no
# Date/Publication: 2019-10-22 08:40:02 UTC
